path: /Users/khaleedpatan/Documents/CAPSTONE 2/backend copy/datasets/final_dataset  # absolute path to dataset
train: train/images  # train images relative to path
val: val/images  # val images relative to path
test: test/images  # test images relative to path

# Classes for pothole severity detection
names:
  0: minor_pothole
  1: medium_pothole
  2: severe_pothole